name: eventra
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  go_router: ^14.8.1
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  google_maps_flutter: ^2.10.1

  # Helper
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  flutter_animate: ^4.5.2

  #UI
  icons_plus: ^5.0.0
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_expandable_fab: ^2.3.0
  syncfusion_flutter_calendar: ^28.2.7
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.5
  introduction_screen: ^3.1.17


  # Controller
  provider: ^6.1.2
  flutter_bloc: ^9.0.0

  # Firebase
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/on_boarding_images/
     - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true